### ISSUE TITLE
Client missing intents Error

### ISSUE THREAD

**Issue by S0L6** [SirTenzin/OTP-Bot#28]
Run the code an this error pops up:

PS C:\Users\bugs0\Documents\OTP-Bot-master> yarn bot:prod
yarn run v1.22.18
$ node otp.js
C:\node_modules\discord.js\src\client\Client.js:548
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\node_modules\discord.js\src\client\Client.js:548:13)
    at new Client (C:\node_modules\discord.js\src\client\Client.js:76:10)
    at Object.<anonymous> (C:\Users\bugs0\Documents\OTP-Bot-master\bot\src\index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\bugs0\Documents\OTP-Bot-master\otp.js:8:13) {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by SirTenzin** [comment]
turn on the message content intent on the discord bot dashboard
